### PR TITLE
Fix build on Node.js 12

### PR DESCRIPTION
**Pull request by 68ec020**
I only fixed the obvious compile errors. When I find some time, I will look into some warnings. So far everything works as expected.

### CODE REVIEW

**Comment by jue89** [comment]
Nice! Thank you for your pull request.

I don't have access to GPIB devices atm. But I'm willing to merge your PR, nevertheless.
But first I'd like to add Travis for build tests. (Or the fancy new GitHub Actions? Maybe a good project for diving in ;)) I want to ensure that this module also builds with less recent Node versions ...

**Comment by jue89** [comment]
Hey!

I just pushed a new branch to my repo. Would you mind testing it out?
https://github.com/jue89/node-linux-gpib/tree/68ec020-node.js-12

I fixed the compiler warnings you mentioned and also fixed a little incompatibility with Node 8 and older that sneaked into the code.

But all in all a nice pull request. Thank you again :)

**Comment by 68ec020** [comment]
It compiled and it works great with a HP 33120A.

**Comment by jue89** [comment]
Nice! I'm going to merge your PR and publish this packages tomorrow night.

**Pull request merged**
